---
# Based on https://github.com/ionelmc/cookiecutter-pylibrary/
sudo: false
language: python
python: '3.5'

before_cache:
  - rm -rf $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip

env:
  - TOXENV=py27,codecov
  - TOXENV=py33,codecov
  - TOXENV=py34,codecov
  - TOXENV=py35,codecov
  - TOXENV=pypy,codecov

install:
  - pip install codecov

script:
  - tox -v

notifications:
  email:
    on_success: never
    on_failure: always
